main.py gestartet
Endpoints other than open requested but private key and certificate are not set.
Listening on 0.0.0.0:4842
Starten des OPC-Monitoring Servers erfolgreich
Verbindung zum OPC Server erfolgreich
subscribed to:  T_D40
subscribed to:  T_tank
subscribed to:  T_kuehl
subscribed to:  r_ist
subscribed to:  F
subscribed to:  TOELE
subscribed to:  s
subscribed to:  state
neue maximalzeit: 0.0292s Zeit: 15:12:12.316013
neue maximalzeit: 0.0295s Zeit: 15:12:12.416185
neue maximalzeit: 0.0297s Zeit: 15:12:12.516343
neue maximalzeit: 0.0304s Zeit: 15:12:12.616505
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
Exception calling data change handler
Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 337, in from_string
    return NodeId._from_string(string)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 352, in _from_string
    k, v = el.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "/home/mister/Desktop/ABB_Projekt/OPC/opcua_client.py", line 26, in datachange_notification
    self.regler.set_input(val,node) # neue daten zum regler schicken
  File "/home/mister/Desktop/ABB_Projekt/Regler/Regler_loop.py", line 47, in set_input
    if node == self.client.client.get_node(f"{namespace};state"):
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/client/client.py", line 538, in get_node
    return Node(self.uaclient, nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/common/node.py", line 49, in __init__
    self.nodeid = ua.NodeId.from_string(nodeid)
  File "/home/mister/.local/lib/python3.9/site-packages/opcua/ua/uatypes.py", line 339, in from_string
    raise UaStringParsingError("Error parsing string {0}".format(string), ex)
opcua.ua.uaerrors._base.UaStringParsingError: ('Error parsing string ns=5;state', ValueError('not enough values to unpack (expected 2, got 1)'))
neue maximalzeit: 0.0330s Zeit: 15:12:12.716664
neue maximalzeit: 0.0350s Zeit: 15:12:12.816834
neue maximalzeit: 0.0374s Zeit: 15:12:13.717858
neue maximalzeit: 0.0384s Zeit: 15:12:13.818030
neue maximalzeit: 0.0394s Zeit: 15:12:14.218490
Keyboard interrupt received. Exiting...
neue maximalzeit: 0.0396s Zeit: 15:12:17.121578
cannot join current thread
close_secure_channel() failed: socket already closed
gestopt :15:12:17.137569
